config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :books
  root 'categories#index'

  # The route names are Turkish
  # Actually, the "resources" method should take a plural argument
  # like "kategoriler" or "gonderiler" (the -ler is plural suffix)
  # But it turned into a strange behavior: "/kategoriler/1" or "/gonderiler/1"
  # So I changed them into a singular form.
  resources :kategori, controller: :categories, as: :categories
  resources :gonderi, controller: :posts, as: :posts do
    resources :comments
  end

  resources :books, param: :name, path: '', except: %i[index edit update destroy]
  get '/:name/:chapter', to: 'books#show'
end

app/models/post.rb
# frozen_string_literal: true

# Posts are classic blog posts, as you know.
# The first paragraph is preview text.
# The first image is repoussoir for post preview.
# When a post is created, the "append_new_post" method updates the page
class Post < ApplicationRecord
  belongs_to :category
  has_many  :comments
  validates :title, presence: true
  validates :body, length: { minimum: 100 }
  has_rich_text :body

  # The main problem with these methods causes N+1 queries.
  # The "ActiveText" things cause this.
  def preview_text
    plain_text = body.to_plain_text
    return plain_text[0..400] unless plain_text.include? "\n"

    plain_text = plain_text.split("\n")

    plain_text.each do
      next if _1.blank?
      return _1 unless _1.starts_with?('[') && _1.ends_with?(']')
    end

    # Turkish: Error while creating post preview
    'Gönderi ön izlemesi oluşturulurken hata oluştu'
  end

  def preview_image
    body.embeds.find(&:image?)
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

# The "Gonderi" routes the URL into the Posts controller.
# Look for the Post model for more information.
# While editing or creating a new post, the post must be auto-saved by server.
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  before_action :require_login, except: %i[index show]

  unless Rails.env.production?
    before_action do
      Prosopite.scan
    end

    after_action do
      Prosopite.finish
    end
  end

  # GET /gonderi or /gonderi.json
  def index
    @pagy, @posts = pagy Post.order('created_at DESC').with_rich_text_body_and_embeds

    respond_to do |format|
      format.html
      format.json do
        render json: {
          posts: render_to_string(
            PostListComponent.new(posts: @posts, pagy: @pagy),
            formats: [:html],
            layout: false
          ),
          pagy: view_context.pagy_nav(@pagy)
        }
      end
    end
  end

  # GET /gonderi/1 or /gonderi/1.json
  def show; end

  # GET /gonderi/new
  def new
    @post = Post.new
  end

  # GET /gonderi/1/edit
  def edit; end

  # POST /gonderi or /gonderi.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gonderi/1 or /gonderi/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gonderi/1 or /gonderi/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to gonderi_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :body, :category_id, :picture)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.haml
.container.my-6{"data-controller": "editor"}
  = form_with model: @post do |form|
    .container
      = form.text_field :title, class: "bg-transparent focus:bg-gray-200 focus:text-black border-0 border-b-2 mb-2 tracking-widest font-light text-2xl"
      = form.rich_text_area :body, class: "dark:bg-black"
      .flex.flex-col.sm:flex-row.sm:justify-between.my-2
        = form.select :category_id, Category.all.map { |i| [i.name, i.id] }, { }, { class: "mb-4 sm:my-0 appearance-none bg-transparent border-0 border-b-2 border-solid" }
        .flex.flex-col.sm:flex-row
          %a.sm:mr-2.hover:bg-gray-700.bg-black.p-2.rounded.antialised.text-white{"data-action": "editor#toggleMenu"} Yeni kategori ekle
          = form.submit "Kaydet", class: "hover:bg-pink-100 hover:text-red-900 text-white bg-black p-2 rounded antialised"
  = turbo_frame_tag "newCategory", "data-editor-target": "newCategoryMenu", src: new_category_path, class: "hidden m-8" do |i|
    #{render HeaderComponent.new.with_content("Yükleniyor")}

app/views/posts/edit.html.haml
.container
  .text-center= render HeaderComponent.new.with_content("#{@post.title} düzenleniyor.")
  = render "form", model: @post
  = render LinkComponent.new.with_content(link_to "Neye benziyor?", @post)

app/views/posts/index.html.haml
= render PostListComponent.new(posts: @posts, pagy: @pagy)

app/views/posts/new.html.haml
.container
  -# Bağlantılı resim nasıl eklenecek?
    Belki de bağlantılı resim yerine içerikteki ilk resmi almalı.
    Başlık çubuğu düzenlebilir olmalı ve başlık olarak kaydedilmeli.
  .text-center= render HeaderComponent.new.with_content("Yeni Gönderi")
  = render "form", post: @post

app/views/posts/show.html.haml
.container
  .text-center.my-6= render HeaderComponent.new.with_content(@post.title)
  %article.p-3.text-medium.trix-content.bg-gray-300.dark:bg-black.antialised.rounded= @post.body
  - if @post.comments.length > 0
    .mt-7= render HeaderComponent.new.with_content("Güzide Yorumlarımız")
    .flex.flex-col.divide-y.divide-opacity-25= render CommentComponent.with_collection(@post.comments)
  = render CommentFormComponent.new(comment: [@post, @post.comments.build])