config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :books
  root 'categories#index'

  # The route names are Turkish
  # Actually, the "resources" method should take a plural argument
  # like "kategoriler" or "gonderiler" (the -ler is plural suffix)
  # But it turned into a strange behavior: "/kategoriler/1" or "/gonderiler/1"
  # So I changed them into a singular form.
  resources :kategori, controller: :categories, as: :categories
  resources :gonderi, controller: :posts, as: :posts do
    resources :comments
  end

  resources :books, param: :name, path: '', except: %i[index edit update destroy]
  get '/:name/:chapter', to: 'books#show'
end

app/models/category.rb
# frozen_string_literal: true

# This model contains posts, also can be used for static pages
class Category < ApplicationRecord
  has_many :posts
  validates :name, length: { in: 5..20 }
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

# This controller manages the Category pages.
# Look for more information in app/models/category.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]
  before_action :require_login, except: %i[index show]

  # GET /categories or /categories.json
  def index
    @pagy, @posts = pagy Post.limit(3).reverse_order
    @category_pagy, @categories = pagy Category.where.not(name: 'Hakkında')
  end

  # GET /categories/1 or /categories/1.json
  def show
    @pagy, @category_posts = pagy @category.posts.order('created_at DESC')

    # This part is just copy-paste from posts#index
    respond_to do |format|
      format.html
      format.json do
        render json: {
          posts: render_to_string(
            PostListComponent.new(posts: @category_posts, pagy: @pagy),
            formats: [:html],
            layout: false
          ),
          pagy: view_context.pagy_nav(@pagy)
        }
      end
    end
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.haml
%div{:id => "#{dom_id category}"}
  %p.my-5
    %strong.block.font-medium.mb-1 Name:
    = category.name
  - if action_name != "show"
    = link_to "Show this category", category, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"
    = link_to 'Edit this category', edit_category_path(category), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium"
    %hr.mt-6/

app/views/categories/_form.html.haml
= form_with model: category do |form|
  .flex.justify-between
    -# Shhh... These classes are copied :')
    = form.text_field :name, class: "bg-transparent hover:bg-gray-200 hover:text-black border-0 border-b-2 m-2 tracking-widest font-light text-2xl"
    = form.submit "Kaydet", class: "hover:bg-pink-100 hover:text-red-900 text-white bg-black p-2 rounded antialised"

app/views/categories/edit.html.haml
.container
  %h1= render HeaderComponent.new.with_content("#{@category}'i düzenle")
  = form_with model: @category do |form|
    .flex.justify-between
      = form.text_field :name
      = form.content :information
      = form.submit

app/views/categories/index.html.haml
.w-full.container.divide-y.hover:divide-double
  %p.text-center.mb-4.antialised.font-sans.font-light
    Adım Emre. Kendi kafamca bir şeyler yazıyorum ve kafayı uzun bir süredir edebiyat ile yazılım ile bozdum. Bir tane de yazdığım bir bilimkurgu kitabım var: #{link_to "Kara Tilki Hiyerarşisi (Tıkla!)", "/karatilkihiyerarsisi", class: "decoration-solid"}. Geveze bir adam olsam da kendimi tarif ederken ne yazık ki yaratıcı olamıyorum.
  .container.flex.flex-col
    = render HeaderComponent.new.with_content "Son gönderiler"
    = render PostListComponent.new(posts: @posts, pagy: @pagy)
    = link_to "diğer güzel şeyler...", posts_path
  .container.flex.flex-col
    - @categories.each do |category|
      = render HeaderComponent.new.with_content "#{category.name} kategorisinden son gönderi"
      -# Okay, this code smells. I just looked for a easy way to saving DRY principle.
      = render PostListComponent.new(posts: category.posts.order(created_at: :desc).limit(1), pagy: @category_pagy)

app/views/categories/new.html.haml
= turbo_frame_tag "newCategory" do
  .container.contents
    %h1= render HeaderComponent.new.with_content("Yeni Kategori Ekle")
    = render "form", category: @category

app/views/categories/show.html.haml
.container
  -# Başa ilgili resim gelecek
  .text-center= render HeaderComponent.new.with_content(@category.name)
  .antialised.text-center.my-6= @category.information
  = render PostListComponent.new(posts: @category_posts, pagy: @pagy)